# Generated by Django 3.2.4 on 2021-06-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.TextField(max_length=753, verbose_name='Heading')),
                ('instagram', models.CharField(blank=True, max_length=150, verbose_name='Instagram')),
                ('PostingDate', models.DateTimeField(auto_now=True, verbose_name='Registration Date')),
                ('type', models.CharField(blank=True, default='img', max_length=5)),
                ('image', models.ImageField(max_length=150, upload_to='')),
                ('url', models.URLField(max_length=150, null=True, validators=[main.models.aresSilka])),
                ('authors_id', models.IntegerField(blank=True, default=1)),
                ('authors_ip', models.CharField(default='', max_length=150, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImageAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
