# Generated by Django 3.2.4 on 2021-06-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authors_ip',
        ),
    ]
